name: Build, Test, Lint, and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run lint
        run: npm run web-ext:lint
        
      - name: Build extension
        run: npm run web-ext:build

      # Step: Extract version and output tag
      - name: Get version from manifest.json
        id: get_version
        run: |
          version=$(jq -r .version src/manifest.json)
          echo "tag=v$version" >> "$GITHUB_OUTPUT"

      - name: Fetch all tags
        run: git fetch --tags
        
      - name: Check if tag already exists
        run: |
          tag=${{ steps.get_version.outputs.tag }}
          echo "Checking if tag $tag exists..."
          if git rev-parse $tag >/dev/null 2>&1; then
            echo "❌ Tag $tag already exists. Aborting."
            echo "Update the version in manifest and package.json"
            exit 1
          fi

      # Step: Create and push Git tag
      - name: Create and push Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.get_version.outputs.tag }}
          git push origin ${{ steps.get_version.outputs.tag }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-containers@${{ steps.get_version.outputs.tag }}
          path: out/*.zip
